### ISSUE TITLE
When assembling on the manual error occurs

### ISSUE THREAD

**Issue by StasToken** [soywiz/haxe-crypto#15]
Hello, I'm trying to collect "hello world" according to the instructions as written here:

https://github.com/v8/v8/wiki/Getting-Started-with-Embedding 

By doing: gn args out.gn/x64.release 

I get an error:

> 
> % gn args out.gn/x64.release                                                                          :(
> Waiting for editor on "/home/master/js_v8/v8/out.gn/x64.release/args.gn"...
> Generating files...
> ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
>     pkgresult = exec_script(pkg_config_script, args, "value")
>                 ^----------
> Current dir: /home/master/js_v8/v8/out.gn/x64.release/
> Command: python -- /home/master/js_v8/v8/build/config/linux/pkg-config.py -s /home/master/js_v8/v8/build/linux/debian_stretch_amd64-sysroot -a x64 glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
> Returned 1.
> stderr:
> 
> Traceback (most recent call last):
>   File "/home/master/js_v8/v8/build/config/linux/pkg-config.py", line 232, in <module>
>     sys.exit(main())
>   File "/home/master/js_v8/v8/build/config/linux/pkg-config.py", line 139, in main
>     prefix = GetPkgConfigPrefixToStrip(options, args)
>   File "/home/master/js_v8/v8/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
>     "--variable=prefix"] + args, env=os.environ)
>   File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> 
> See //build/config/linux/BUILD.gn:83:3: whence it was called.
>   pkg_config("glib") {
>   ^-------------------
> See //build/config/compiler/BUILD.gn:191:18: which caused the file to be included.
>     configs += [ "//build/config/linux:compiler" ]
>                  ^------------------------------
> 

Prompt how to be? How to fix it?

**Comment by soywiz** [comment]
Looks like you filled the issue in the wrong repo.
