### ISSUE TITLE
low entropy random seeding

### ISSUE THREAD

**Issue by thomasuster** [soywiz/haxe-crypto#3]
https://github.com/soywiz/haxe-crypto/blob/557195fd4ae22890d32724c100f1a5885d24db6e/src/com/hurlant/util/System.hx#L12

std.random will only have about 117k seeds

**Comment by soywiz** [comment]
I can use javascript getSecureRandomBytes on js target,
and in other targets like swf or c++ i could use other information.
Any suggestions on that?

**Comment by thomasuster** [comment]
Hey, yea I can't find a UUID library for C++. So I'll be making my own UUID Library with some kind of cool randomness. Would you like me to share that with you when you're done? Maybe you can use some code in this lib from it.

**Comment by thomasuster** [comment]
@soywiz I tried a haxe-only implementation and was unable to get enough randomness(~48 bits worth) instead of required 128 bits. Attempt here https://github.com/thomasuster/uuid/blob/master/src/thomasuster/UUIDFactory.hx

I ended up writing an NME extension, since my app is android & iOS. And then using this in my own lib for wrapping UUID by md5'ing 4 random ints, upperCasing ,and splitting with dashes. https://github.com/thomasuster/extension-secureRandom

**Comment by thomasuster** [comment]
Feel free to close if you want, your call, I'd recommend doing something though. If someone writes an APP assuming high entropy first UUID startup (account IDs), then consequences could be very bad. https://github.com/andyli/casahx and other libs I've found have the same problem.

**Comment by soywiz** [comment]
Haxe should provide something for proper random generation in its core API, so anybody can use that as a source of entropy. Something like a SecureRandom in haxe.crypto package. (maybe we could make a PR).
In the meantime I can create a function here, with `#if` per target using the best method for each language.
JS: crypto.getRandomValues(new Int8Array(x))
AS3:
http://help.adobe.com/en_US/FlashPlatform/beta/reference/actionscript/3/flash/crypto/package.html#generateRandomBytes()
Old versions: https://github.com/timkurvers/as3-crypto/blob/master/src/com/hurlant/crypto/prng/Random.as#L64
SYS: /dev/random if available, or your solution if not available
PHP:
http://php.net/manual/en/function.random-bytes.php
https://github.com/paragonie/random_compat
PYTHON: os.urandom(10)
JAVA: https://docs.oracle.com/javase/7/docs/api/java/security/SecureRandom.html
C#: https://msdn.microsoft.com/en-us/library/system.security.cryptography.randomnumbergenerator.aspx

**Comment by soywiz** [comment]
In nodejs: https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback

**Comment by soywiz** [comment]
Done

**Comment by soywiz** [comment]
https://github.com/HaxeFoundation/haxe/issues/5033

**Comment by thomasuster** [comment]
Wow! You can access the java package in haxe??? https://github.com/soywiz/haxe-crypto/blob/master/src/com/hurlant/crypto/prng/SecureRandom.hx#L32

**Comment by soywiz** [comment]
Yep. 
https://github.com/HaxeFoundation/hxjava/tree/master/lib

OpenJDK is included and it detects all the exposed classes.
